const activity = {
  image: {
    baseball: require('../../../../../App/Assets/Images/Activities/baseball.png'),
    basketball: require('../../../../../App/Assets/Images/Activities/basketball.png'),
    biking: require('../../../../../App/Assets/Images/Activities/biking.png'),
    cheer: require('../../../../../App/Assets/Images/Activities/cheer.png'),
    football: require('../../../../../App/Assets/Images/Activities/football.png'),
    golf: require('../../../../../App/Assets/Images/Activities/golf.png'),
    gymnastics: require('../../../../../App/Assets/Images/Activities/gymnastics.png'),
    hockey: require('../../../../../App/Assets/Images/Activities/hockey.png'),
    lacrosse: require('../../../../../App/Assets/Images/Activities/lacrosse.png'),
    running: require('../../../../../App/Assets/Images/Activities/running.png'),
    scootering: require('../../../../../App/Assets/Images/Activities/scootering.png'),
    skateboarding: require('../../../../../App/Assets/Images/Activities/skateboarding.png'),
    skiing: require('../../../../../App/Assets/Images/Activities/skiing.png'),
    soccer: require('../../../../../App/Assets/Images/Activities/soccer.png'),
    surfing: require('../../../../../App/Assets/Images/Activities/surfing.png'),
    swimming: require('../../../../../App/Assets/Images/Activities/swimming.png'),
    tennis: require('../../../../../App/Assets/Images/Activities/tennis.png'),
    volleyball: require('../../../../../App/Assets/Images/Activities/volleyball.png'),
    weightlifting: require('../../../../../App/Assets/Images/Activities/weightlifting.png'),
    yoga: require('../../../../../App/Assets/Images/Activities/yoga.png'),
    jumprope: require('../../../../../App/Assets/Images/Activities/jumprope.png'),
    hike: require('../../../../../App/Assets/Images/Activities/hike.png'),
    walk: require('../../../../../App/Assets/Images/Activities/walk.png'),
    martialarts: require('../../../../../App/Assets/Images/Activities/martialarts.png'),
    happy: require('../../../../../App/Assets/Images/Moods/happy.png'),
    loved: require('../../../../../App/Assets/Images/Moods/loved.png'),
    silly: require('../../../../../App/Assets/Images/Moods/silly.png'),
    confident: require('../../../../../App/Assets/Images/Moods/confident.png'),
    excited: require('../../../../../App/Assets/Images/Moods/excited.png'),
    relaxed: require('../../../../../App/Assets/Images/Moods/relaxed.png'),
    confused: require('../../../../../App/Assets/Images/Moods/confused.png'),
    bored: require('../../../../../App/Assets/Images/Moods/bored.png'),
    tired: require('../../../../../App/Assets/Images/Moods/tired.png'),
    frustrated: require('../../../../../App/Assets/Images/Moods/frustrated.png'),
    stressed: require('../../../../../App/Assets/Images/Moods/stressed.png'),
    nervous: require('../../../../../App/Assets/Images/Moods/nervous.png'),
    worried: require('../../../../../App/Assets/Images/Moods/worried.png'),
    lonely: require('../../../../../App/Assets/Images/Moods/lonely.png'),
    hurt: require('../../../../../App/Assets/Images/Moods/hurt.png'),
    sick: require('../../../../../App/Assets/Images/Moods/sick.png'),
    angry: require('../../../../../App/Assets/Images/Moods/angry.png'),
    sad: require('../../../../../App/Assets/Images/Moods/sad.png'),
    depressed: require('../../../../../App/Assets/Images/Moods/depressed.png'),
    overwhelmed: require('../../../../../App/Assets/Images/Moods/overwhelmed.png'),
    hopeful: require('../../../../../App/Assets/Images/Moods/hopeful.png'),
    grateful: require('../../../../../App/Assets/Images/Moods/grateful.png'),
    disappointed: require('../../../../../App/Assets/Images/Moods/disappointed.png'),
    annoyed: require('../../../../../App/Assets/Images/Moods/annoyed.png'),
    goofy: require('../../../../../App/Assets/Images/Moods/silly.png'),
    scared: require('../../../../../App/Assets/Images/Moods/afraid.png'),
  }
};

export default activity;
