const activity = {
  image: {
    Basketball: require('../../../../../App/Assets/Images/Activities/basketball.png'),
    Biking: require('../../../../../App/Assets/Images/Activities/biking.png'),
    Cheer: require('../../../../../App/Assets/Images/Activities/cheer.png'),
    Football: require('../../../../../App/Assets/Images/Activities/football.png'),
    Golf: require('../../../../../App/Assets/Images/Activities/golf.png'),
    Gymnastics: require('../../../../../App/Assets/Images/Activities/gymnastics.png'),
    Hockey: require('../../../../../App/Assets/Images/Activities/hockey.png'),
    Lacrosse: require('../../../../../App/Assets/Images/Activities/lacrosse.png'),
    Running: require('../../../../../App/Assets/Images/Activities/running.png'),
    Scootering: require('../../../../../App/Assets/Images/Activities/scootering.png'),
    Skateboarding: require('../../../../../App/Assets/Images/Activities/skateboarding.png'),
    Skiing: require('../../../../../App/Assets/Images/Activities/skiing.png'),
    Soccer: require('../../../../../App/Assets/Images/Activities/soccer.png'),
    Surfing: require('../../../../../App/Assets/Images/Activities/surfing.png'),
    Swimming: require('../../../../../App/Assets/Images/Activities/swimming.png'),
    Tennis: require('../../../../../App/Assets/Images/Activities/tennis.png'),
    Volleyball: require('../../../../../App/Assets/Images/Activities/volleyball.png'),
    Weightlifting: require('../../../../../App/Assets/Images/Activities/weightlifting.png'),
    Yoga: require('../../../../../App/Assets/Images/Activities/yoga.png'),
    JumpRope: require('../../../../../App/Assets/Images/Activities/jumprope.png'),
    Hike: require('../../../../../App/Assets/Images/Activities/hike.png'),
    Walk: require('../../../../../App/Assets/Images/Activities/walk.png'),
    MartialArts: require('../../../../../App/Assets/Images/Activities/martialarts.png'),
    Happy: require('../../../../../App/Assets/Images/Moods/happy.png'),
    Loved: require('../../../../../App/Assets/Images/Moods/loved.png'),
    Silly: require('../../../../../App/Assets/Images/Moods/silly.png'),
    Confident: require('../../../../../App/Assets/Images/Moods/confident.png'),
    Excited: require('../../../../../App/Assets/Images/Moods/excited.png'),
    Relaxed: require('../../../../../App/Assets/Images/Moods/relaxed.png'),
    Confused: require('../../../../../App/Assets/Images/Moods/confused.png'),
    Bored: require('../../../../../App/Assets/Images/Moods/bored.png'),
    Tired: require('../../../../../App/Assets/Images/Moods/tired.png'),
    Frustrated: require('../../../../../App/Assets/Images/Moods/frustrated.png'),
    Stressed: require('../../../../../App/Assets/Images/Moods/stressed.png'),
    Nervous: require('../../../../../App/Assets/Images/Moods/nervous.png'),
    Worried: require('../../../../../App/Assets/Images/Moods/worried.png'),
    Lonely: require('../../../../../App/Assets/Images/Moods/lonely.png'),
    Hurt: require('../../../../../App/Assets/Images/Moods/hurt.png'),
    Sick: require('../../../../../App/Assets/Images/Moods/sick.png'),
    Mad: require('../../../../../App/Assets/Images/Moods/angry.png'),
    Sad: require('../../../../../App/Assets/Images/Moods/sad.png'),
    Depressed: require('../../../../../App/Assets/Images/Moods/depressed.png'),
    Overwhelmed: require('../../../../../App/Assets/Images/Moods/overwhelmed.png'),
    Hopeful: require('../../../../../App/Assets/Images/Moods/hopeful.png'),
    Grateful: require('../../../../../App/Assets/Images/Moods/grateful.png'),
    Disappointed: require('../../../../../App/Assets/Images/Moods/disappointed.png'),
    Annoyed: require('../../../../../App/Assets/Images/Moods/annoyed.png'),
    Goofy: require('../../../../../App/Assets/Images/Moods/silly.png'),
    Scared: require('../../../../../App/Assets/Images/Moods/afraid.png'),
  }
};

export default activity;
