const activity = {
  image: {
    baseball: require('../../../Assets/Images/Activities/baseball.png'),
    basketball: require('../../../Assets/Images/Activities/basketball.png'),
    biking: require('../../../Assets/Images/Activities/biking.png'),
    cheer: require('../../../Assets/Images/Activities/cheer.png'),
    football: require('../../../Assets/Images/Activities/football.png'),
    golf: require('../../../Assets/Images/Activities/golf.png'),
    gymnastics: require('../../../Assets/Images/Activities/gymnastics.png'),
    hockey: require('../../../Assets/Images/Activities/hockey.png'),
    lacrosse: require('../../../Assets/Images/Activities/lacrosse.png'),
    running: require('../../../Assets/Images/Activities/running.png'),
    scootering: require('../../../Assets/Images/Activities/scootering.png'),
    skateboarding: require('../../../Assets/Images/Activities/skateboarding.png'),
    skiing: require('../../../Assets/Images/Activities/skiing.png'),
    soccer: require('../../../Assets/Images/Activities/soccer.png'),
    surfing: require('../../../Assets/Images/Activities/surfing.png'),
    swimming: require('../../../Assets/Images/Activities/swimming.png'),
    tennis: require('../../../Assets/Images/Activities/tennis.png'),
    volleyball: require('../../../Assets/Images/Activities/volleyball.png'),
    weightlifting: require('../../../Assets/Images/Activities/weightlifting.png'),
    yoga: require('../../../Assets/Images/Activities/yoga.png'),
    jumprope: require('../../../Assets/Images/Activities/jumprope.png'),
    hike: require('../../../Assets/Images/Activities/hike.png'),
    walk: require('../../../Assets/Images/Activities/walk.png'),
    martialarts: require('../../../Assets/Images/Activities/martialarts.png'),
    happy: require('../../../Assets/Images/Moods/happy.png'),
    loved: require('../../../Assets/Images/Moods/loved.png'),
    silly: require('../../../Assets/Images/Moods/silly.png'),
    confident: require('../../../Assets/Images/Moods/confident.png'),
    excited: require('../../../Assets/Images/Moods/excited.png'),
    relaxed: require('../../../Assets/Images/Moods/relaxed.png'),
    confused: require('../../../Assets/Images/Moods/confused.png'),
    bored: require('../../../Assets/Images/Moods/bored.png'),
    tired: require('../../../Assets/Images/Moods/tired.png'),
    frustrated: require('../../../Assets/Images/Moods/frustrated.png'),
    stressed: require('../../../Assets/Images/Moods/stressed.png'),
    nervous: require('../../../Assets/Images/Moods/nervous.png'),
    worried: require('../../../Assets/Images/Moods/worried.png'),
    lonely: require('../../../Assets/Images/Moods/lonely.png'),
    hurt: require('../../../Assets/Images/Moods/hurt.png'),
    sick: require('../../../Assets/Images/Moods/sick.png'),
    angry: require('../../../Assets/Images/Moods/angry.png'),
    sad: require('../../../Assets/Images/Moods/sad.png'),
    depressed: require('../../../Assets/Images/Moods/depressed.png'),
    overwhelmed: require('../../../Assets/Images/Moods/overwhelmed.png'),
    hopeful: require('../../../Assets/Images/Moods/hopeful.png'),
    grateful: require('../../../Assets/Images/Moods/grateful.png'),
    disappointed: require('../../../Assets/Images/Moods/disappointed.png'),
    annoyed: require('../../../Assets/Images/Moods/annoyed.png'),
    goofy: require('../../../Assets/Images/Moods/silly.png'),
    scared: require('../../../Assets/Images/Moods/afraid.png'),
  }
};

export default activity;
